#!/bin/bash

# Script para corrigir os caminhos do backup no servidor

echo "======================================"
echo "CORREÇÃO DOS CAMINHOS DE BACKUP"
echo "======================================"
echo ""
echo "Execute estes comandos no servidor como root:"
echo ""
echo "cd /opt/sistema-gestao-softwares"
echo ""
echo "# Verificar se os scripts existem na pasta scripts/"
echo "ls -la scripts/backup.sh scripts/restore.sh"
echo ""
echo "# Criar links simbólicos no diretório raiz do projeto"
echo "ln -sf scripts/backup.sh backup.sh"
echo "ln -sf scripts/restore.sh restore.sh"
echo ""
echo "# Tornar executáveis (caso necessário)"
echo "chmod +x scripts/backup.sh scripts/restore.sh"
echo "chmod +x backup.sh restore.sh"
echo ""
echo "# Testar se funciona"
echo "sistema-gestao backup"
echo ""
echo "======================================"
echo "ALTERNATIVA: Editar o script sistema-gestao"
echo "======================================"
echo ""
echo "Se preferir, edite /usr/local/bin/sistema-gestao"
echo "e ajuste a linha do backup para:"
echo ""
echo "        backup)"
echo "            cd /opt/sistema-gestao-softwares"
echo "            ./scripts/backup.sh"
echo "            ;;"
echo ""
echo "E adicione também o restore:"
echo ""
echo "        restore)"
echo "            cd /opt/sistema-gestao-softwares"
echo "            ./scripts/restore.sh \"\$2\""
echo "            ;;"