#!/bin/bash

# Script para corrigir o comando de backup no servidor

echo "Este script deve ser executado no servidor como root:"
echo ""
echo "# No servidor, execute:"
echo "cd /opt/sistema-gestao-softwares"
echo ""
echo "# Criar link simbólico para o script de backup"
echo "ln -sf /opt/sistema-gestao-softwares/scripts/backup.sh /opt/sistema-gestao-softwares/backup.sh"
echo ""
echo "# Criar link simbólico para o script de restore"
echo "ln -sf /opt/sistema-gestao-softwares/scripts/restore.sh /opt/sistema-gestao-softwares/restore.sh"
echo ""
echo "# Ou adicionar os comandos ao script sistema-gestao:"
echo "cat << 'EOF' >> /usr/local/bin/sistema-gestao"
echo "        backup)"
echo "            cd /opt/sistema-gestao-softwares"
echo "            ./scripts/backup.sh"
echo "            ;;"
echo "        restore)"
echo "            cd /opt/sistema-gestao-softwares"
echo "            ./scripts/restore.sh \"\$2\""
echo "            ;;"
echo "EOF"